Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-18.10"
  config.vm.provision "shell", inline: <<-SHELL
     apt-get update
     apt-get install -y build-essential
     apt-get install -y gfortran
     ln -s /usr/bin/env /bin/env
  SHELL
  config.vm.provision "file", source: "../general/init-asgs.sh",   destination: "$HOME/init-asgs.sh"
  config.vm.provision "file", source: "../general/README.vagrant", destination: "$HOME/README.vagranth"
end
